services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: smart-agri-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
      
    environment:
      - MONGO_URI=mongodb+srv://parikshitwaghmare31_db_user:Amruta1999@cluster0.pn6exd2.mongodb.net/?appName=Cluster0
      - MONGO_DB_NAME=smart_agriculture
      - MQTT_BROKER_HOST=gf81afde.ala.asia-southeast1.emqxsl.com
      - MQTT_BROKER_PORT=8883
      - MQTT_TOPIC=farm/sensors
      - MQTT_USE_TLS=true
      - MQTT_USERNAME=smartagri_mqtt
      - MQTT_PASSWORD=Amruta031999
      - MODEL_PATH=/app/ml/models/irrigation_model.pkl
      - CORS_ORIGINS=*

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: smart-agri-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  iot-simulator:
    build:
      context: .
      dockerfile: docker/Dockerfile.simulator
    container_name: smart-agri-simulator
    restart: unless-stopped
    environment:
      - MQTT_BROKER_HOST=gf81afde.ala.asia-southeast1.emqxsl.com
      - MQTT_BROKER_PORT=8883
      - MQTT_TOPIC=farm/sensors
      - MQTT_USE_TLS=true
      - MQTT_USERNAME=smartagri_mqtt
      - MQTT_PASSWORD=Amruta031999
